### ISSUE TITLE
When gulp-watching, the bundle and test tasks run in parallel

### ISSUE THREAD

**Issue by liady** [casesandberg/react-map-styles#3]
When running gulp in watch mode, on every change the `bundle` and `test` tasks run in parallel,
which often make the tests run on the old bundled js code.

There are 2 possible solutions:
#### 1. Add as dependency

set `bundle` as a dependency to `test`, like this:

``` js
gulp.task('test', ['bundle'], function(){
  return gulp.src('./test/**/*.coffee')
             .pipe(mocha());
});
```

and have `bundle` return its stream:

``` js
gulp.task('bundle', function(done) {
  return gulp.src('./src/**/*.coffee')
            .pipe(coffee({bare: true}))
            .pipe(gulp.dest('lib'));
});
```
#### 2. Use plugin

use the [run-sequence](https://www.npmjs.com/package/run-sequence) plugin in order to run them in sequence: https://github.com/gulpjs/gulp/issues/670

**Comment by casesandberg** [comment]
Thanks @liady, just got this out!

https://github.com/casesandberg/react-map-styles/blob/master/gulpfile.js#L14
