### ISSUE TITLE
what is this?

### ISSUE THREAD

**Issue by joewalnes** [casesandberg/react-map-styles#5]
I ended up here following a link on the reactcss README. But I have no idea what this library actually does and why I'd need it. Any chance of getting a high level overview on the README?

**Comment by casesandberg** [comment]
I will work a little write up this week!

**Comment by adamdicarlo** [comment]
Looks like a webpack loader that uses regex to transform JSX `to={...}` prop expressions into `style={...}` or some such?

**Comment by casesandberg** [comment]
This has been deprecated and is no longer necessary for reactcss
