### ISSUE TITLE
Support for setting mutliple classes

### ISSUE THREAD

**Issue by mwildehahn** [casesandberg/react-map-styles#7]
There are times when I want to be able to have something like the following:

``` js
classes() {
    return {
        default: {
            container: {
                display: 'flex',
            },
            containerA: {
                backgroundColor: 'blue',
            },
            containerB: {
                backgroundColor: 'red',
            },
        },
    };
}

render() {
    return (
        <div>
            <div is="container containerA" />
            <div is="container containerB" />
        </div>
    );
}

```

basically, having a common class that applies to more than one element.

right now I do this:

``` js

classes() {
    const common = {
        container: {
            display: 'flex',
        }
    };
    return {
        default: {
            containerA: {
                backgroundColor: 'blue',
                ...common.container,
            },
            containerB: {
                backgroundColor: 'red',
                ...common.container,
            },
        },
    };
}

render() {
    return (
        <div>
            <div is="containerA" />
            <div is="containerB" />
        </div>
    );
}
```

what I don't like about the above is that reactcss can't control common. with the first one i could create different rules and change the values of "container" that would apply to everything.

one proposal is to split on space within "is" -- i don't feel great about this since you could technically have:

``` js
classes() {
     return {
           default: {
                "a valid but annoying rule": {},
           },
     }
}
```

maybe a new keyword like "merge", "combine"?

**Comment by casesandberg** [comment]
Ah, yeah you hit on a good point. There actually is an Extend mixin in ReactCSS! This is exactly what you are looking for:

https://github.com/casesandberg/react-color/blob/9e8fff4e527067f8680f4d349592629400df406b/src/components/photoshop/Photoshop.jsx#L118

**Comment by mwildehahn** [comment]
oh awesome, thanks!
