### ISSUE TITLE
browserify support

### ISSUE THREAD

**Issue by digitalsurgeon** [casesandberg/react-map-styles#9]
Seems to me that react-map-styles is a webpack loader. I want to use it in a browserify project, so what do you think would be the fastest way to achieve this ?

I basically want to use reactcss in my project which is based on browserify.

**Comment by casesandberg** [comment]
It's super easy! You can just create a custom transform like this:

```
var through = require('through2');
var mapStyles = require('react-map-styles');

module.exports = function (file) {
    return through(function (buf, enc, next) {
        this.push(mapStyles(buf.toString('utf8')));
        next();
    });
};
```

You can read more info here: https://github.com/substack/browserify-handbook#writing-your-own. The `react-map-styles` plugin is just exporting a function, you just need to call it!
